defmodule Tunez.Repo.Migrations.AddAlbumNotificationFanOut do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tunez_queue_schedules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenant, :text
      add :name, :text, null: false
      add :state, :text, default: "active"
      add :kind, :text
      add :condition, :text, default: "clock"
      add :watch_resource, :text
      add :watch, :binary
      add :reap_on_fire, :boolean, default: false
      add :cron, :text
      add :timezone, :text, default: "Etc/UTC"
      add :guaranteed, :boolean, default: false
      add :insertions, {:array, :utc_datetime}, default: []
      add :queue, :text
      add :worker, :text
      add :target, :binary
      add :args, :binary
      add :meta, :binary
      add :priority, :bigint, default: 0
      add :tags, {:array, :text}, default: []
      add :max_attempts, :bigint, default: 20
      add :list_tenants, :map, default: %{}
      add :actor_persister, :text
      add :actor_ref, :binary
      add :shared_context, :binary
      add :context, :binary
      add :next_run_at, :utc_datetime_usec
      add :last_run_at, :utc_datetime_usec
      add :managed_by, :text, default: "seed"
      add :seed_key, :text
      add :seed_hash, :text
      add :inserted_at, :utc_datetime_usec
      add :updated_at, :utc_datetime_usec
    end

    create index(:tunez_queue_schedules, [:managed_by, :seed_key],
             name: "tunez_queue_schedules_managed_by_seed_key_idx"
           )

    create index(:tunez_queue_schedules, [:queue, :state, :next_run_at, :id],
             name: "tunez_queue_schedules_queue_state_next_run_at_id_idx"
           )

    create index(:tunez_queue_schedules, [:state, :next_run_at, :id],
             name: "tunez_queue_schedules_state_next_run_at_id_idx"
           )

    create table(:tunez_queue_keys, primary_key: false) do
      add :key, :text, null: false, primary_key: true
      add :reservation_kind, :text, null: false, default: "unique"
      add :job_id, :uuid
      add :states, {:array, :text}, default: []
      add :expires_at, :utc_datetime_usec
      add :generation, :bigint, null: false, default: 0
      add :inserted_at, :utc_datetime_usec
      add :updated_at, :utc_datetime_usec
    end

    create index(:tunez_queue_keys, [:reservation_kind, :expires_at, :key],
             name: "tunez_queue_keys_reservation_kind_expires_at_key_idx"
           )

    create index(:tunez_queue_keys, [:expires_at, :key],
             name: "tunez_queue_keys_expires_at_key_idx"
           )

    create index(:tunez_queue_keys, [:job_id, :key], name: "tunez_queue_keys_job_id_key_idx")

    create table(:tunez_queue_jobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :queue, :text, null: false
      add :state, :text, null: false, default: "available"
      add :priority, :bigint, null: false, default: 0
      add :worker, :text
      add :kind, :text, default: "worker_call"
      add :args, :binary
      add :meta, :binary
      add :tags, {:array, :text}, default: []
      add :attempt, :bigint, default: 0
      add :max_attempts, :bigint, default: 20
      add :attempted_by, :binary
      add :attempted_at, :utc_datetime_usec

      add :scheduled_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :orig_scheduled_at, :utc_datetime_usec
      add :inserted_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :discarded_at, :utc_datetime_usec
      add :cancelled_at, :utc_datetime_usec
      add :expires_at, :utc_datetime_usec
      add :unique_key, :text
      add :unique_scope, :binary
      add :tenant, :text
      add :actor_ref, :binary
      add :actor_persister, :text
      add :context, :binary
      add :trace_id, :text
      add :last_error, :binary
      add :errors, :binary
      add :rescued, :bigint, default: 0
      add :snoozed, :bigint, default: 0
    end

    create index(:tunez_queue_jobs, [:tenant, :queue, :state, :priority, :scheduled_at, :id],
             name: "tunez_queue_jobs_tenant_queue_state_priority_scheduled_id_idx"
           )

    create index(:tunez_queue_jobs, [:queue, :state, :expires_at, :id],
             name: "tunez_queue_jobs_queue_state_expires_id_idx"
           )

    create index(:tunez_queue_jobs, [:queue, :state, :attempted_at, :id],
             name: "tunez_queue_jobs_queue_state_attempted_id_idx"
           )

    create index(:tunez_queue_jobs, [:queue, :state, :scheduled_at, :id],
             name: "tunez_queue_jobs_queue_state_scheduled_id_idx"
           )

    create index(:tunez_queue_jobs, [:state, :expires_at, :id],
             name: "tunez_queue_jobs_state_expires_id_idx"
           )

    create index(:tunez_queue_jobs, [:state, :attempted_at, :id],
             name: "tunez_queue_jobs_state_attempted_id_idx"
           )

    create index(:tunez_queue_jobs, [:state, :scheduled_at, :id],
             name: "tunez_queue_jobs_state_scheduled_id_idx"
           )

    create index(:tunez_queue_jobs, [:queue, :state, :priority, :scheduled_at, :id],
             name: "tunez_queue_jobs_queue_state_priority_scheduled_id_idx"
           )

    create table(:tunez_queue_controls, primary_key: false) do
      add :control_kind, :text, null: false, primary_key: true
      add :key, :text, null: false, primary_key: true
      add :name, :text
      add :tenant, :text
      add :state, :text, default: "active"
      add :limit, :bigint, default: 20
      add :local_limit, :bigint
      add :min_claim_batch, :bigint
      add :max_claim_wait_ms, :bigint
      add :global_limit, :map, default: %{}
      add :paused_until, :utc_datetime_usec
      add :rate_limit, :map, default: %{}
      add :partition, :map, default: %{}
      add :retention, :map, default: %{}
      add :managed_by, :text, default: "seed"
      add :seed_key, :text
      add :seed_hash, :text
      add :owner, :text
      add :token, :text
      add :expires_at, :utc_datetime_usec
      add :generation, :bigint, null: false, default: 0
      add :event_kind, :text
      add :payload, :binary
      add :inserted_at, :utc_datetime_usec
      add :updated_at, :utc_datetime_usec
    end

    create index(:tunez_queue_controls, [:control_kind, :inserted_at, :key],
             name: "tunez_queue_controls_kind_inserted_at_key_idx"
           )

    create index(:tunez_queue_controls, [:control_kind, :expires_at, :key],
             name: "tunez_queue_controls_kind_expires_at_key_idx"
           )

    create index(:tunez_queue_controls, [:control_kind, :managed_by, :seed_key],
             name: "tunez_queue_controls_kind_managed_by_seed_key_idx"
           )

    create index(:tunez_queue_controls, [:control_kind, :tenant, :name],
             name: "tunez_queue_controls_kind_tenant_name_idx"
           )

    create index(:tunez_queue_controls, [:control_kind, :name],
             name: "tunez_queue_controls_kind_name_idx"
           )

    create index(:tunez_queue_controls, [:control_kind, :state, :name],
             name: "tunez_queue_controls_kind_state_name_idx"
           )

    create unique_index(:notifications, [:album_id, :user_id],
             name: "notifications_one_per_album_follower_index"
           )
  end

  def down do
    drop_if_exists unique_index(:notifications, [:album_id, :user_id],
                     name: "notifications_one_per_album_follower_index"
                   )

    drop_if_exists index(:tunez_queue_controls, [:control_kind, :state, :name],
                     name: "tunez_queue_controls_kind_state_name_idx"
                   )

    drop_if_exists index(:tunez_queue_controls, [:control_kind, :name],
                     name: "tunez_queue_controls_kind_name_idx"
                   )

    drop_if_exists index(:tunez_queue_controls, [:control_kind, :tenant, :name],
                     name: "tunez_queue_controls_kind_tenant_name_idx"
                   )

    drop_if_exists index(:tunez_queue_controls, [:control_kind, :managed_by, :seed_key],
                     name: "tunez_queue_controls_kind_managed_by_seed_key_idx"
                   )

    drop_if_exists index(:tunez_queue_controls, [:control_kind, :expires_at, :key],
                     name: "tunez_queue_controls_kind_expires_at_key_idx"
                   )

    drop_if_exists index(:tunez_queue_controls, [:control_kind, :inserted_at, :key],
                     name: "tunez_queue_controls_kind_inserted_at_key_idx"
                   )

    drop table(:tunez_queue_controls)

    drop_if_exists index(:tunez_queue_jobs, [:queue, :state, :priority, :scheduled_at, :id],
                     name: "tunez_queue_jobs_queue_state_priority_scheduled_id_idx"
                   )

    drop_if_exists index(:tunez_queue_jobs, [:state, :scheduled_at, :id],
                     name: "tunez_queue_jobs_state_scheduled_id_idx"
                   )

    drop_if_exists index(:tunez_queue_jobs, [:state, :attempted_at, :id],
                     name: "tunez_queue_jobs_state_attempted_id_idx"
                   )

    drop_if_exists index(:tunez_queue_jobs, [:state, :expires_at, :id],
                     name: "tunez_queue_jobs_state_expires_id_idx"
                   )

    drop_if_exists index(:tunez_queue_jobs, [:queue, :state, :scheduled_at, :id],
                     name: "tunez_queue_jobs_queue_state_scheduled_id_idx"
                   )

    drop_if_exists index(:tunez_queue_jobs, [:queue, :state, :attempted_at, :id],
                     name: "tunez_queue_jobs_queue_state_attempted_id_idx"
                   )

    drop_if_exists index(:tunez_queue_jobs, [:queue, :state, :expires_at, :id],
                     name: "tunez_queue_jobs_queue_state_expires_id_idx"
                   )

    drop_if_exists index(
                     :tunez_queue_jobs,
                     [:tenant, :queue, :state, :priority, :scheduled_at, :id],
                     name: "tunez_queue_jobs_tenant_queue_state_priority_scheduled_id_idx"
                   )

    drop table(:tunez_queue_jobs)

    drop_if_exists index(:tunez_queue_keys, [:job_id, :key],
                     name: "tunez_queue_keys_job_id_key_idx"
                   )

    drop_if_exists index(:tunez_queue_keys, [:expires_at, :key],
                     name: "tunez_queue_keys_expires_at_key_idx"
                   )

    drop_if_exists index(:tunez_queue_keys, [:reservation_kind, :expires_at, :key],
                     name: "tunez_queue_keys_reservation_kind_expires_at_key_idx"
                   )

    drop table(:tunez_queue_keys)

    drop_if_exists index(:tunez_queue_schedules, [:state, :next_run_at, :id],
                     name: "tunez_queue_schedules_state_next_run_at_id_idx"
                   )

    drop_if_exists index(:tunez_queue_schedules, [:queue, :state, :next_run_at, :id],
                     name: "tunez_queue_schedules_queue_state_next_run_at_id_idx"
                   )

    drop_if_exists index(:tunez_queue_schedules, [:managed_by, :seed_key],
                     name: "tunez_queue_schedules_managed_by_seed_key_idx"
                   )

    drop table(:tunez_queue_schedules)
  end
end
